[git]
conventional_commits = false
filter_unconventional = false
sort_commits = "oldest"
tag-prefix = ""

[changelog]
trim = false

[parser]
tag = "glob:v*"

[[parser.conventional]]
match = "^fix"
group = "ğŸ› Bug Fixes"

[[parser.conventional]]
match = "^feat"
group = "âœ¨ Features"

[[parser.conventional]]
match = "^update"
group = "ğŸ”§ Updates"

[[parser.conventional]]
match = ".*"
group = "ğŸ’¼ Other"
