[git]
tag-prefix = ""

[parser]
tag = "glob:v*"

[[parser.bump]]
match = "BREAKING"

[[parser.conventional]]
match = "feat"

[[parser.conventional]]
match = "fix"

[[parser.conventional]]
match = "update"