name: Build & Release krview

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  ZIG_VERSION: 0.15.2

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: krview-linux.tar.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      # ---------- SDL ----------
      - name: Install SDL (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

      #vcpkg install sdl2 sdl2-ttf sdl2-image    
      # I pray for windows to die
      - name: Build (Linux/Mac)
        if: matrix.os != 'windows-latest'
        run: |
          zig build -Doptimize=ReleaseFast -Dcpu=baseline
        shell: bash

            # ---------- PACKAGE ---------
      - name: Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          mkdir -p krview/assets/fonts
          mkdir -p krview/assets/screenshots
          mkdir -p krview/lib

          cp zig-out/bin/krview krview/
          chmod +x krview/krview

          cp assets/fonts/Terminus.ttf krview/assets/fonts/
          cp assets/fonts/OFL.TXT krview/assets/fonts/

          sudo apt-get install -y patchelf

          ldd zig-out/bin/krview \
          | sed -n 's/.*=> \(\/[^ ]*\).*/\1/p' \
          | grep -vE 'libc.so|ld-linux|linux-vdso' \
          | sort -u \
          | while read -r lib; do
              echo "Copying $lib"
              cp -v "$lib" krview/lib/
            done

          patchelf --set-rpath '$ORIGIN/lib' krview/krview

          tar -czf ${{ matrix.artifact }} krview
          mkdir -p dist
          mv ${{ matrix.artifact }} dist/${{ matrix.artifact }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/krview-linux.tar.gz



            
